/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.edu.uni.centromedico.ui.panels;

/**
 *
 * @author hector0-0
 */
public class AdminCitasPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminCitasPanel
     */
    public AdminCitasPanel() {
        initComponents();

        // Especialidades se cargan dinámicamente desde AdminCitasController
        cmb_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Todas"}));
        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Todos", "PENDIENTE", "ATENDIDA", "CANCELADA"
        }));

        pnl_filtros.setLayout(new net.miginfocom.swing.MigLayout(
            "fillx, insets 0", "[grow][grow][]", "[36!]"
        ));
        pnl_filtros.removeAll();
        pnl_filtros.add(cmb_especialidad, "growx, h 36!");
        pnl_filtros.add(cmb_estado,       "growx, h 36!, gapleft 8");
        pnl_filtros.add(btn_filtrar,      "h 36!, gapleft 8");

        tbl_citas_admin.setRowHeight(36);
        scrl_citas_admin.setBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232,221,216)));

        this.setLayout(new net.miginfocom.swing.MigLayout(
            "fill, insets 24", "[grow]", "[]12[]12[grow]"
        ));
        this.removeAll();
        this.add(lbl_titulo,       "wrap");
        this.add(pnl_filtros,      "growx, wrap");
        this.add(scrl_citas_admin, "grow");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        pnl_filtros = new javax.swing.JPanel();
        cmb_especialidad = new javax.swing.JComboBox<>();
        cmb_estado = new javax.swing.JComboBox<>();
        btn_filtrar = new javax.swing.JButton();
        scrl_citas_admin = new javax.swing.JScrollPane();
        tbl_citas_admin = new javax.swing.JTable();

        lbl_titulo.setText("Todas las Citas");

        cmb_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_filtrar.setText("Filtrar");

        tbl_citas_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Paciente", "Especialidad", "Médico", "Fecha", "Estado"
            }
        ));
        scrl_citas_admin.setViewportView(tbl_citas_admin);

        javax.swing.GroupLayout pnl_filtrosLayout = new javax.swing.GroupLayout(pnl_filtros);
        pnl_filtros.setLayout(pnl_filtrosLayout);
        pnl_filtrosLayout.setHorizontalGroup(
            pnl_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_filtrosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnl_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_filtrar)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_filtrosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmb_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_filtrosLayout.createSequentialGroup()
                        .addComponent(scrl_citas_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE))))
        );
        pnl_filtrosLayout.setVerticalGroup(
            pnl_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_filtrosLayout.createSequentialGroup()
                .addGroup(pnl_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_filtrosLayout.createSequentialGroup()
                        .addComponent(cmb_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrl_citas_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_filtrar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lbl_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pnl_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lbl_titulo)
                .addGap(39, 39, 39)
                .addComponent(pnl_filtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // ── API pública para AdminCitasController ────────────────────────────
    public javax.swing.JTable            getTblCitasAdmin()    { return tbl_citas_admin; }
    public javax.swing.JButton           getBtnFiltrar()       { return btn_filtrar; }
    public javax.swing.JComboBox<String> getCmbEspecialidad()  { return cmb_especialidad; }
    public javax.swing.JComboBox<String> getCmbEstado()        { return cmb_estado; }

    public void setEspecialidades(java.util.List<String> especialidades) {
        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
        model.addElement("Todas");
        especialidades.forEach(model::addElement);
        cmb_especialidad.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_filtrar;
    private javax.swing.JComboBox<String> cmb_especialidad;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_filtros;
    private javax.swing.JScrollPane scrl_citas_admin;
    private javax.swing.JTable tbl_citas_admin;
    // End of variables declaration//GEN-END:variables
}
