/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.edu.uni.centromedico.ui.panels;

/**
 *
 * @author hector0-0
 */
public class GestionStockPanel extends javax.swing.JPanel {

    
    public GestionStockPanel() {
        initComponents();

        pnl_acciones.setLayout(new net.miginfocom.swing.MigLayout(
            "fillx, insets 0", "[grow][][][]", "[36!]"
        ));
        pnl_acciones.removeAll();
        pnl_acciones.add(txt_buscar_stock, "growx, h 36!");
        pnl_acciones.add(btn_buscar_stock, "h 36!, gapleft 8");
        pnl_acciones.add(btn_agregar_stock,"h 36!, gapleft 4");

        tbl_stock.setRowHeight(36);
        scrl_stock.setBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232,221,216)));

        this.setLayout(new net.miginfocom.swing.MigLayout(
            "fill, insets 24", "[grow]", "[]12[]12[grow]"
        ));
        this.removeAll();
        this.add(lbl_titulo,    "wrap");
        this.add(pnl_acciones,  "growx, wrap");
        this.add(scrl_stock,    "grow");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        pnl_acciones = new javax.swing.JPanel();
        scrl_stock = new javax.swing.JScrollPane();
        tbl_stock = new javax.swing.JTable();
        txt_buscar_stock = new javax.swing.JTextField();
        btn_buscar_stock = new javax.swing.JButton();
        btn_agregar_stock = new javax.swing.JButton();

        lbl_titulo.setText("Gestión de Medicamentos");

        tbl_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Stock", "Unidad", "Acción"
            }
        ));
        scrl_stock.setViewportView(tbl_stock);

        javax.swing.GroupLayout pnl_accionesLayout = new javax.swing.GroupLayout(pnl_acciones);
        pnl_acciones.setLayout(pnl_accionesLayout);
        pnl_accionesLayout.setHorizontalGroup(
            pnl_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_accionesLayout.setVerticalGroup(
            pnl_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_buscar_stock.setText("Buscar");

        btn_agregar_stock.setText("+ Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_buscar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_agregar_stock)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar_stock)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_titulo)
                .addGap(28, 28, 28)
                .addComponent(pnl_acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_buscar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar_stock)
                    .addComponent(btn_agregar_stock))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_stock;
    private javax.swing.JButton btn_buscar_stock;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_acciones;
    private javax.swing.JScrollPane scrl_stock;
    private javax.swing.JTable tbl_stock;
    private javax.swing.JTextField txt_buscar_stock;
    // End of variables declaration//GEN-END:variables
}
