# src/main/resources/config.properties — SQL Server
db.host=localhost
db.port=1433
db.name=centro_medico
db.user=sa
db.password=123
# Si usas una instancia con nombre (ej: SQLEXPRESS), descomenta:
# db.instance=SQLEXPRESS
db.instance=
